model:
  model_name: "/home/mamba/ML_project/Testing/Huy/joint_vlm/viper-vlm/pretrained/mamba-1.5b"
  ckpt_path: "/home/mamba/ML_project/Testing/Huy/joint_vlm/viper-vlm/pretrained/vision_siglip"
  tokenizer: "/home/mamba/ML_project/Testing/Huy/joint_vlm/viper_tokenier"
  stage: 1

dataset:
  image_path: "/home/mamba/ML_project/Testing/Huy/joint_vlm/dataset/cc_3m/images/"
  json_path: "/home/mamba/ML_project/Testing/Huy/joint_vlm/dataset/cc_3m/chat.json"

logging:
  filename: 'logs/training.log'

# add more configs here