siglip:
  ckpt_path: "/home/mamba/ML_project/Testing/Huy/joint_vlm/viper-vlm/pretrained/vision_siglip"
  tokenizer: "/home/mamba/ML_project/Testing/Huy/joint_vlm/viper_tokenier"

dataset:
  image_path: "/home/mamba/ML_project/Testing/Huy/joint_vlm/dataset/cc_3m/images/"
  json_path: "/home/mamba/ML_project/Testing/Huy/joint_vlm/dataset/cc_3m/chat.json"

logs:
  filename: 'logs/training.log'